name: Release Drafter

on:
  push:
    branches:
    - master
    - feature/ace-build
    - blank

jobs:
  draft:
    runs-on: ubuntu-latest
    if: github.repository == 'Gehock/zeusopsmod'
    steps:
    - name: Release Drafter
      uses: release-drafter/release-drafter@v5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
